/* ============================================================
   helpers.js  —  PR #0 FROZEN.  Shared UI primitives under
   ChipViz.*  so sections look consistent and agents don't
   reinvent toggles/counters/tables. Need something extra?
   Build it INSIDE your section file — do not edit this file.
   ============================================================ */
(function (ChipViz) {
  'use strict';
  var SVGNS = 'http://www.w3.org/2000/svg';

  /** Create an HTML element. props supports className, text, html, on{Event}, dataset, style, and attributes. */
  function el(tag, props, children) {
    var node = document.createElement(tag);
    applyProps(node, props);
    appendChildren(node, children);
    return node;
  }

  /** Create a namespaced SVG element. */
  function svg(tag, attrs, children) {
    var node = document.createElementNS(SVGNS, tag);
    if (attrs) {
      Object.keys(attrs).forEach(function (k) {
        if (k === 'text') node.textContent = attrs[k];
        else node.setAttribute(k, attrs[k]);
      });
    }
    appendChildren(node, children);
    return node;
  }

  function applyProps(node, props) {
    if (!props) return;
    Object.keys(props).forEach(function (k) {
      var v = props[k];
      if (k === 'className') node.className = v;
      else if (k === 'text') node.textContent = v;
      else if (k === 'html') node.innerHTML = v;
      else if (k === 'dataset') Object.keys(v).forEach(function (d) { node.dataset[d] = v[d]; });
      else if (k === 'style' && typeof v === 'object') Object.assign(node.style, v);
      else if (k.indexOf('on') === 0 && typeof v === 'function') node.addEventListener(k.slice(2).toLowerCase(), v);
      else if (v != null) node.setAttribute(k, v);
    });
  }

  function appendChildren(node, children) {
    if (children == null) return;
    (Array.isArray(children) ? children : [children]).forEach(function (c) {
      if (c == null) return;
      node.appendChild(typeof c === 'string' ? document.createTextNode(c) : c);
    });
  }

  function prefersReducedMotion() {
    return window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  }

  /**
   * Animate a signal pulse along an SVG <line> or <path>.
   * Falls back to a brief color flash under reduced motion.
   * color defaults to var(--accent).
   */
  function pulse(wireEl, color) {
    if (!wireEl) return;
    color = color || getComputedStyle(document.documentElement).getPropertyValue('--accent').trim();
    if (prefersReducedMotion()) {
      var prev = wireEl.getAttribute('stroke');
      wireEl.setAttribute('stroke', color);
      setTimeout(function () { if (prev) wireEl.setAttribute('stroke', prev); }, 200);
      return;
    }
    var len;
    try { len = wireEl.getTotalLength(); } catch (e) { len = 100; }
    wireEl.style.stroke = color;
    wireEl.style.strokeDasharray = len + ' ' + len;
    wireEl.style.strokeDashoffset = String(len);
    wireEl.style.transition = 'none';
    // force reflow then animate the dash offset to 0
    void wireEl.getBoundingClientRect();
    wireEl.style.transition = 'stroke-dashoffset 600ms var(--ease)';
    wireEl.style.strokeDashoffset = '0';
  }

  /**
   * Clickable 0/1 bit toggle.
   * opts = { value?:0|1, label?:string, onChange?:fn(value) }
   * returns { el, get(), set(v), value }
   */
  function bitToggle(opts) {
    opts = opts || {};
    var state = opts.value ? 1 : 0;
    var btn = el('button', {
      className: 'cv-bit',
      type: 'button',
      'aria-label': (opts.label || 'bit') + ' = ' + state,
      text: String(state)
    });
    function render() {
      btn.textContent = String(state);
      btn.dataset.on = state ? '1' : '0';
      btn.setAttribute('aria-label', (opts.label || 'bit') + ' = ' + state);
    }
    btn.addEventListener('click', function () {
      state = state ? 0 : 1;
      render();
      if (opts.onChange) opts.onChange(state);
    });
    render();
    var api = { el: btn, get: function () { return state; },
      set: function (v) { state = v ? 1 : 0; render(); } };
    Object.defineProperty(api, 'value', { get: function () { return state; } });
    return api;
  }

  /**
   * Live numeric readout.
   * returns { el, set(n), label }
   */
  function counter(label) {
    var val = el('span', { className: 'cv-counter-val mono-num', text: '0' });
    var wrap = el('span', { className: 'cv-counter' }, [
      el('span', { className: 'cv-counter-label', text: label + ': ' }), val
    ]);
    return { el: wrap, set: function (n) { val.textContent = String(n); } };
  }

  /**
   * Truth table.
   * cols: array of header strings. rows: array of arrays (strings/numbers).
   * returns { el, highlightRow(i) }
   */
  function truthTable(cols, rows) {
    var thead = el('tr', null, cols.map(function (c) { return el('th', { text: String(c) }); }));
    var bodyRows = rows.map(function (r) {
      return el('tr', null, r.map(function (cell) { return el('td', { text: String(cell) }); }));
    });
    var table = el('table', { className: 'cv-truth' }, [
      el('thead', null, thead),
      el('tbody', null, bodyRows)
    ]);
    return {
      el: table,
      highlightRow: function (i) {
        bodyRows.forEach(function (tr, idx) { tr.dataset.active = (idx === i) ? '1' : '0'; });
      }
    };
  }

  /**
   * Tiny SVG bar chart.
   * data: array of { label, value, color? }.
   * returns { el, update(data) }
   */
  function barChart(initial) {
    var W = 280, H = 140, pad = 24;
    var root = svg('svg', { viewBox: '0 0 ' + W + ' ' + H, class: 'cv-bars', width: '100%' });
    function update(data) {
      while (root.firstChild) root.removeChild(root.firstChild);
      var max = Math.max.apply(null, data.map(function (d) { return d.value; }).concat([1]));
      var bw = (W - pad * 2) / data.length * 0.6;
      var gap = (W - pad * 2) / data.length;
      data.forEach(function (d, i) {
        var h = (H - pad * 2) * (d.value / max);
        var x = pad + i * gap + (gap - bw) / 2;
        var y = H - pad - h;
        root.appendChild(svg('rect', { x: x, y: y, width: bw, height: h, rx: 3,
          fill: d.color || 'var(--accent)' }));
        root.appendChild(svg('text', { x: x + bw / 2, y: H - pad + 14, 'text-anchor': 'middle',
          fill: 'var(--text-muted)', 'font-size': '10', 'font-family': 'var(--font-mono)', text: d.label }));
        root.appendChild(svg('text', { x: x + bw / 2, y: y - 4, 'text-anchor': 'middle',
          fill: 'var(--text)', 'font-size': '11', 'font-family': 'var(--font-mono)', text: String(d.value) }));
      });
    }
    update(initial || []);
    return { el: root, update: update };
  }

  ChipViz.el = el;
  ChipViz.svg = svg;
  ChipViz.pulse = pulse;
  ChipViz.bitToggle = bitToggle;
  ChipViz.counter = counter;
  ChipViz.truthTable = truthTable;
  ChipViz.barChart = barChart;
  ChipViz.prefersReducedMotion = prefersReducedMotion;
})(window.ChipViz);
